# Main workflow for building and publishing the project nuxeo-studio-components-common
name: Nuxeo Studio Components Common build with Maven

on:
  pull_request:
    types: [opened, synchronize]
    branches: [master]
  push:
    branches: [master]
    tags: 'v[0-9]+.[0-9]+.[0-9]+'

env:
  M2_SETTINGS: ${{ secrets.M2_YAYA_SETTINGS }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Allow jgitver versionning by fetching all tags and branches

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: maven

      # Write m2 settings file with credentials for accessing
      # private nexus repository.
      - name: Setup maven
        run: echo $M2_SETTINGS > ~/.m2/settings.xml

      - name: Force branch name for jgitver on PR
        if: ${{ github.event_name == 'pull_request'}}
        run: git checkout ${GITHUB_HEAD_REF}

      - name: Force fetching remote tags for jgitver releases
        run: git fetch --tags -f

      - name: Build with Maven
        run: mvn package

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'

      - name: Publish with Maven
        run: mvn deploy -DskipTests -DrepositoryId=packages.nuxeo.com